// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication.asp.net.c3.Data;

#nullable disable

namespace WebApplication.asp.net.c3.Migrations
{
    [DbContext(typeof(ProductCatalogDbContext))]
    partial class ProductCatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication.asp.net.c3.Models.Brand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_brands_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_brands_name");

                    b.ToTable("brands", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Виробник процесорів",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Intel",
                            Website = "https://www.intel.com"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Лідер у виробництві процесорів",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "AMD",
                            Website = "https://www.amd.com"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Лідер у виробництві відеокарт",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "NVIDIA",
                            Website = "https://www.nvidia.com"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Виробник материнських плат та відеокарт",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "ASUS",
                            Website = "https://www.asus.com"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Виробник материнських плат, відеокарт та периферії",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "MSI",
                            Website = "https://www.msi.com"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Виробник материнських плат та відеокарт",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gigabyte",
                            Website = "https://www.gigabyte.com"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Виробник пам'яті, БЖ та периферії",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Corsair",
                            Website = "https://www.corsair.com"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Виробник пам'яті та накопичувачів",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kingston",
                            Website = "https://www.kingston.com"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Виробник SSD накопичувачів та пам'яті",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Samsung",
                            Website = "https://www.samsung.com"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Виробник HDD та SSD накопичувачів",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Western Digital",
                            Website = "https://www.westerndigital.com"
                        });
                });

            modelBuilder.Entity("WebApplication.asp.net.c3.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("ParentCategoryId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_name");

                    b.HasIndex("ParentCategoryId")
                        .HasDatabaseName("ix_categories_parent_category_id");

                    b.HasIndex("IsActive", "SortOrder")
                        .HasDatabaseName("ix_categories_is_active_sort_order");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Центральні процесори для ПК",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Процесори",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Материнські плати для різних платформ",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Материнські плати",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Графічні процесори та відеокарти",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Відеокарти",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "DDR4 та DDR5 модулі пам'яті",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Оперативна пам'ять",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SSD та HDD накопичувачі",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Накопичувачі",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Твердотільні накопичувачі",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "SSD накопичувачі",
                            ParentCategoryId = 5L,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Жорсткі диски",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "HDD накопичувачі",
                            ParentCategoryId = 5L,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Блоки живлення для ПК",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Блоки живлення",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Корпуси для збірки ПК",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Корпуси",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Системи охолодження для ПК",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Охолодження",
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("WebApplication.asp.net.c3.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<long>("BrandId")
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DetailedDescription")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<decimal?>("DiscountedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("SKU")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsFeatured")
                        .HasDatabaseName("ix_products_is_featured");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_products_name");

                    b.HasIndex("SKU")
                        .IsUnique()
                        .HasDatabaseName("ix_products_sku")
                        .HasFilter("\"SKU\" IS NOT NULL");

                    b.HasIndex("BrandId", "IsActive")
                        .HasDatabaseName("ix_products_brand_id_is_active");

                    b.HasIndex("CategoryId", "IsActive")
                        .HasDatabaseName("ix_products_category_id_is_active");

                    b.HasIndex("Price", "IsActive")
                        .HasDatabaseName("ix_products_price_is_active");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_average_rating_range", "\"AverageRating\" IS NULL OR (\"AverageRating\" >= 0 AND \"AverageRating\" <= 5)");

                            t.HasCheckConstraint("ck_products_discounted_price_positive", "\"DiscountedPrice\" IS NULL OR \"DiscountedPrice\" > 0");

                            t.HasCheckConstraint("ck_products_price_positive", "\"Price\" > 0");

                            t.HasCheckConstraint("ck_products_stock_quantity_non_negative", "\"StockQuantity\" >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AverageRating = 4.7999999999999998,
                            BrandId = 1L,
                            CategoryId = 1L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "24-ядерний процесор для високопродуктивних систем",
                            DetailedDescription = "Intel Core i9-14900K - флагманський процесор 14-го покоління з 24 ядрами (8P+16E), 32 потоками, базовою частотою 3.2 GHz та турбо до 6.0 GHz. Сокет LGA1700, TDP 125W (253W max).",
                            DiscountedPrice = 23499.00m,
                            IsActive = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Name = "Intel Core i9-14900K",
                            Price = 24999.00m,
                            ReviewCount = 47,
                            SKU = "CPU-INTEL-I9-14900K",
                            StockQuantity = 15,
                            Tags = "cpu,intel,gaming,workstation,lga1700"
                        },
                        new
                        {
                            Id = 2L,
                            AverageRating = 4.9000000000000004,
                            BrandId = 2L,
                            CategoryId = 1L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "16-ядерний процесор на архітектурі Zen 4",
                            DetailedDescription = "AMD Ryzen 9 7950X - топовий 16-ядерний процесор з 32 потоками, базовою частотою 4.5 GHz та Boost до 5.7 GHz. Сокет AM5, TDP 170W, підтримка DDR5 та PCIe 5.0.",
                            IsActive = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Name = "AMD Ryzen 9 7950X",
                            Price = 22999.00m,
                            ReviewCount = 63,
                            SKU = "CPU-AMD-R9-7950X",
                            StockQuantity = 22,
                            Tags = "cpu,amd,gaming,workstation,am5,zen4"
                        },
                        new
                        {
                            Id = 3L,
                            AverageRating = 4.7000000000000002,
                            BrandId = 1L,
                            CategoryId = 1L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "14-ядерний процесор середнього рівня",
                            DetailedDescription = "Intel Core i5-14600K - 14-ядерний процесор (6P+8E) з 20 потоками, базовою частотою 3.5 GHz та турбо до 5.3 GHz. Сокет LGA1700, TDP 125W.",
                            DiscountedPrice = 11999.00m,
                            IsActive = true,
                            IsDeleted = false,
                            IsFeatured = false,
                            Name = "Intel Core i5-14600K",
                            Price = 12999.00m,
                            ReviewCount = 89,
                            SKU = "CPU-INTEL-I5-14600K",
                            StockQuantity = 35,
                            Tags = "cpu,intel,gaming,mainstream,lga1700"
                        },
                        new
                        {
                            Id = 4L,
                            AverageRating = 4.9000000000000004,
                            BrandId = 4L,
                            CategoryId = 2L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Преміум материнська плата для Intel 14-го покоління",
                            DetailedDescription = "ASUS ROG MAXIMUS Z790 HERO - топова материнська плата на чіпсеті Z790, сокет LGA1700. Підтримка DDR5-7800+, PCIe 5.0, WiFi 6E, 2.5G LAN, RGB підсвічування AURA Sync.",
                            IsActive = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Name = "ASUS ROG MAXIMUS Z790 HERO",
                            Price = 18999.00m,
                            ReviewCount = 34,
                            SKU = "MB-ASUS-Z790-HERO",
                            StockQuantity = 12,
                            Tags = "motherboard,asus,z790,lga1700,ddr5,gaming"
                        },
                        new
                        {
                            Id = 5L,
                            AverageRating = 4.5999999999999996,
                            BrandId = 5L,
                            CategoryId = 2L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Материнська плата для AMD Ryzen 7000",
                            DetailedDescription = "MSI MAG B650 TOMAHAWK WIFI - материнська плата на чіпсеті B650, сокет AM5. Підтримка DDR5-6400+, PCIe 5.0, WiFi 6E, 2.5G LAN, RGB підсвічування Mystic Light.",
                            DiscountedPrice = 8999.00m,
                            IsActive = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Name = "MSI MAG B650 TOMAHAWK WIFI",
                            Price = 9499.00m,
                            ReviewCount = 56,
                            SKU = "MB-MSI-B650-TOMAHAWK",
                            StockQuantity = 28,
                            Tags = "motherboard,msi,b650,am5,ddr5,gaming"
                        },
                        new
                        {
                            Id = 6L,
                            AverageRating = 5.0,
                            BrandId = 4L,
                            CategoryId = 3L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Найпотужніша геймерська відеокарта",
                            DetailedDescription = "ASUS ROG Strix RTX 4090 - флагманська відеокарта на базі NVIDIA Ada Lovelace. 24GB GDDR6X, 16384 CUDA ядер, частота до 2640 MHz, 3x DisplayPort 1.4a, 2x HDMI 2.1, RGB підсвічування AURA Sync.",
                            IsActive = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            Name = "ASUS ROG Strix GeForce RTX 4090",
                            Price = 79999.00m,
                            ReviewCount = 28,
                            SKU = "GPU-ASUS-RTX4090-STRIX",
                            StockQuantity = 5,
                            Tags = "gpu,nvidia,rtx4090,gaming,4k,raytracing"
                        });
                });

            modelBuilder.Entity("WebApplication.asp.net.c3.Models.ProductAttribute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Name")
                        .HasDatabaseName("ix_product_attributes_product_id_name");

                    b.HasIndex("ProductId", "SortOrder")
                        .HasDatabaseName("ix_product_attributes_product_id_sort_order");

                    b.ToTable("product_attributes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Ядра / Потоки",
                            ProductId = 1L,
                            SortOrder = 1,
                            Value = "24 (8P+16E) / 32"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Базова частота",
                            ProductId = 1L,
                            SortOrder = 2,
                            Unit = "GHz",
                            Value = "3.2"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Ядра / Потоки",
                            ProductId = 2L,
                            SortOrder = 1,
                            Value = "16 / 32"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Сокет",
                            ProductId = 2L,
                            SortOrder = 2,
                            Value = "AM5"
                        });
                });

            modelBuilder.Entity("WebApplication.asp.net.c3.Models.ProductImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AltText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "IsPrimary")
                        .HasDatabaseName("ix_product_images_product_id_is_primary");

                    b.HasIndex("ProductId", "SortOrder")
                        .HasDatabaseName("ix_product_images_product_id_sort_order");

                    b.ToTable("product_images", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AltText = "Intel Core i9-14900K",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/products/intel-i9-14900k-1.jpg",
                            IsDeleted = false,
                            IsPrimary = true,
                            ProductId = 1L,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2L,
                            AltText = "AMD Ryzen 9 7950X",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/products/amd-ryzen9-7950x-1.jpg",
                            IsDeleted = false,
                            IsPrimary = true,
                            ProductId = 2L,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3L,
                            AltText = "ASUS ROG MAXIMUS Z790 HERO",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/products/asus-z790-hero-1.jpg",
                            IsDeleted = false,
                            IsPrimary = true,
                            ProductId = 4L,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 4L,
                            AltText = "ASUS ROG Strix RTX 4090",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/products/asus-rtx4090-strix-1.jpg",
                            IsDeleted = false,
                            IsPrimary = true,
                            ProductId = 6L,
                            SortOrder = 1
                        });
                });

            modelBuilder.Entity("WebApplication.asp.net.c3.Models.ProductReview", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Rating")
                        .HasDatabaseName("ix_product_reviews_rating");

                    b.HasIndex("ProductId", "IsApproved")
                        .HasDatabaseName("ix_product_reviews_product_id_is_approved");

                    b.ToTable("product_reviews", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_reviews_rating_range", "\"Rating\" >= 1 AND \"Rating\" <= 5");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ApprovedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            ApprovedBy = "admin",
                            Comment = "Використовую для стрімінгу. Справляється на ура!",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "alex@example.com",
                            CustomerName = "Олександр Коваленко",
                            IsApproved = true,
                            IsDeleted = false,
                            ProductId = 1L,
                            Rating = 5,
                            Title = "Звір процесор!"
                        },
                        new
                        {
                            Id = 2L,
                            ApprovedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ApprovedBy = "admin",
                            Comment = "16 ядер Zen 4 - це потужність!",
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerEmail = "dmytro@example.com",
                            CustomerName = "Дмитро Петренко",
                            IsApproved = true,
                            IsDeleted = false,
                            ProductId = 2L,
                            Rating = 5,
                            Title = "Ідеальний для workstation"
                        });
                });

            modelBuilder.Entity("WebApplication.asp.net.c3.Models.Category", b =>
                {
                    b.HasOne("WebApplication.asp.net.c3.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("WebApplication.asp.net.c3.Models.Product", b =>
                {
                    b.HasOne("WebApplication.asp.net.c3.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication.asp.net.c3.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebApplication.asp.net.c3.Models.ProductAttribute", b =>
                {
                    b.HasOne("WebApplication.asp.net.c3.Models.Product", "Product")
                        .WithMany("ProductAttributes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApplication.asp.net.c3.Models.ProductImage", b =>
                {
                    b.HasOne("WebApplication.asp.net.c3.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApplication.asp.net.c3.Models.ProductReview", b =>
                {
                    b.HasOne("WebApplication.asp.net.c3.Models.Product", "Product")
                        .WithMany("ProductReviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApplication.asp.net.c3.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebApplication.asp.net.c3.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("WebApplication.asp.net.c3.Models.Product", b =>
                {
                    b.Navigation("ProductAttributes");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
